on:
    push:
      branches:
        - testing
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v3
  
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run the application (optional)
          run: |
            python app.py
  
        - name: Output build information
          run: echo "Build complete"
  