on:
    push:
      branches:
        - testing
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        # Step 1: Checkout code
        - name: Get Code
          uses: actions/checkout@v3
  
        # Step 2: Set up Python 3.10
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
  
        # Step 3: Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        # Step 4: Run the Flask application using Gunicorn in the background
        - name: Run the application with Gunicorn
          run: |
            gunicorn --bind 0.0.0.0:8080 app:app &
            
        
  
        # Step 6: Output build information (optional)
        - name: Output build information
          run: echo "Build complete"
  