on:
    push:
      branches:
        - main
  
jobs:
    test:
      environment: testing
      runs-on: ubuntu-latest
      steps:
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
            
        - name: Get Code
          uses: actions/checkout@v3
          
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run tests
          run: |
            pip install pytest
            pytest test.py
  
        - name: Output information
          run: echo "Test job complete"
  
    build:
      needs: test
      runs-on: ubuntu-latest
  
      steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run the application with Gunicorn
          run: |
            gunicorn --bind 0.0.0.0:8080 app:app &
        - name: Output build information
          run: echo "Build complete"
  
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v3
          
        - name: Deploy
          run: echo "Deployment steps go here"
  